### ISSUE TITLE
Varlist at idle screen issues

### ISSUE THREAD

**Issue by Pinacolada64** [Pinacolada64/ImageBBS#1]
Hopefully this is a gentle introduction to issue tracking for @x-tec2017.

There are a few issues with the idle screen variable display module `+/lo.varlist`.

* Displays string variable name instead of string contents:
![broken-varlist](https://user-images.githubusercontent.com/7505860/33236409-6943e550-d207-11e7-9575-99509e5de730.png)

* Goes into infinite loop when displaying array variable contents: 
![varlist-loop](https://user-images.githubusercontent.com/7505860/33236862-dea736cc-d215-11e7-9abd-517af32a3207.png)

**Comment by x-tec2017** [comment]
Varlist issue is known. Space bar or / key will abort array loop.  +/lo.varlist is original as received from Al. No attempt to fix as of yet.
User displays 141/1 due to failure to create u.index properly during installation.
