### ISSUE TITLE
+/lo.automaint - e.logweek function not working

### ISSUE THREAD

**Issue by x-tec2017** [Pinacolada64/ImageBBS#10]

**Comment by x-tec2017** [comment]
Automaint should create e.logweek on Sunday and append e.log to it during the week.

**Comment by Pinacolada64** [comment]
Is `e.logweek` all of the previous week's logs concatenated together?

**Comment by x-tec2017** [comment]
I think the creation of e.logweek may be a remnant left over from a
previous version. It looks to me like it took whatever was contained in
e.log and appended it day by day to e.logweek. On Sunday, it would create a
new e.logweek file. The e.log file is no longer being used, the automaint
routine now creates e.log x files where x=the number of the day of the
week.

**Comment by Pinacolada64** [comment]
Just out of morbid curiosity to see if I can get it to work: commit https://github.com/Pinacolada64/ImageBBS/commit/e6c69fcf124113c0ea47efa9bfbcf01fcbb81978

**Comment by Pinacolada64** [comment]
Some line number changes: comit https://github.com/Pinacolada64/ImageBBS/commit/7e29741ff835ae5b2956d0fcd27679c9d84fffe4

**Comment by Pinacolada64** [comment]
Hmm, this version puts some stuff before the `e.log x` file. Will look into that.
![broken-log](https://user-images.githubusercontent.com/7505860/34191625-4dac3ee2-e4fd-11e7-8e79-d7b916fd318b.png)
