### ISSUE TITLE
Netmail configuration utility in 2.0 format needed

### ISSUE THREAD

**Issue by x-tec2017** [Pinacolada64/ImageBBS#11]
Printed out +.IM and +.NM/config and evaluated. Working on renumbering and converting +.NM/config to IM module format.

**Comment by Pinacolada64** [comment]
How is this going? I tend to think we could make `+.IM` more modular.

**Comment by x-tec2017** [comment]
I thought about that but when I looked at the ecs commands, most of the
things that call to line numbers in im are just jumps to load modules.

**Comment by x-tec2017** [comment]
Oops.  You're referring to +.IM, not im. Maybe you are right.  I'll have to
look at that.

**Comment by Pinacolada64** [comment]
Right, `+.IM`. :smile: 

So there's a call to `+.IM.netmail` but we don't have that module. It's not in Jack's files, either. Looks like a fun little project.

**Comment by x-tec2017** [comment]
I started working on the netmail module for +.IM but got sidetracked while
getting ready for Christmas. I have a plan, just need time to work on it.

**Comment by Pinacolada64** [comment]
No worries! Sounds cool, would love to see your progress when you get the time.

**Comment by x-tec2017** [comment]
As far as I am concerned, this issue can be closed. The new files are working well.

**Comment by Pinacolada64** [comment]
A little rewrite of the menu numbering when editing node connections (can't edit the node name) and this should be a great addition to the IM suite. There may be one or more tiny tweaks I'd like to make (display `???` instead of `^` for missing node connections) but that's trivial.

Great job on this mod, @x-tec2017 😄

**Comment by x-tec2017** [comment]
If you are seeing ^'s for missing node connections, that's not normal but
I've seen it happen before. Any node connections not assigned should just
remain blank. Sometimes, just exiting from the NM/config and reentering it
will get rid of the ^'s but there have been times when I had to delete the
nm.connect file and then go back into NM/config. Usually that will make the
missing nodes display as blank.

**Comment by x-tec2017** [comment]
And by the way, that ^ issue is not peculiar to 2.0. It happens in 1.2 as
well.
