### ISSUE TITLE
More Prompt - Messages Only is broke

### ISSUE THREAD

**Issue by x-tec2017** [Pinacolada64/ImageBBS#15]
This is a 2 part problem when the More Prompt is set to Messages Only
1. Doesn't pause messages in the Sub Boards.
2. Entering MP causes "Illegal Quantity Error in 1870"

**Comment by x-tec2017** [comment]
The More Prompt variable is held as the 2nd character in the uf$ variable.
0=Off
1=On
2=Messages Only
Entering MP is an ecs command gosub1882

**Comment by Pinacolada64** [comment]
I think I fixed this.

`im`:
1882 b=2:b$="{f5}More?{f5} Prompt":gosub1871:&,52,34,a:return

1882 im=3:goto2406 (loads "im.params")

`im.params`:
60000 onimgoto60004,60056,`60114`,60094,60096

**Comment by ThaDoctor72** [comment]
It would be good if we could force the temporary disabling of prompts during MCI read of a file. Example:
printing on the same line for overlay MCI effect is still counted as a "line", even though the screen does not advance.  System screens with these MCI effects are paused during play, and the more prompt will place the cursor out of expected sequence.

**Comment by Pinacolada64** [comment]
That's a good point, @ThaDoctor72 .

https://github.com/Pinacolada64/ImageBBS/blob/72067e1076070638bd9ce22ecf6a831d820abe75/v2/docs/lightbar.txt#L71

Left `Mor` (I assume) turns off the More prompt. Right `Mor` says the More prompt isn't available. I don't know what the difference is. We'll have to experiment to find out which toggle would be more effective.

**Comment by Pinacolada64** [comment]
I'm having trouble downloading the latest .d81s from Facebook. Can someone confirm that Left `Mor` is toggled on after setting `MP` mode to 2 (On) or 3 (Messages Only) in `im.misc`? if not, we should add that. Something like `60117 &,52,34,sgn(abs(a>1))` should do it. `Mor` mode will be reset for options 2 and 3, cleared for option 1.

**Comment by x-tec2017** [comment]
It already done. Check mark is included.
