### ISSUE TITLE
NISSA "size" utility reports incorrect block size

### ISSUE THREAD

**Issue by Pinacolada64** [Pinacolada64/ImageBBS#2]
This is `size` from the Christmas 1994 NISSA disk. Try running it multiple times (`sys 52992`) with the same program in memory. The block size keeps increasing (one less than the total blocks, it seems) between runs. The block size should be initialized to zero between runs.

**Comment by x-tec2017** [comment]
You either have to put the program on LU 10 of a Lt.Kernal and type size every time you want to use it or you have to reload "size",dv#,1 and type the sys52992.  This ml program written by Ray Kelm uses memory to determine the size of a file so each time you run it, more memory gets used up.

**Comment by Pinacolada64** [comment]
Okay, that's a valid way of using it. I don't have a Lt. Kernal hard drive anymore, alas. But I can save a reload and thus increase the convenience of using the program by just sticking one or two instructions in the code which zero out the block counter. I worked on disassembling it earlier today and once I find the byte(s) which count the block size, it's a simple matter of patching it. :)

**Comment by Pinacolada64** [comment]
Fixed that issue: put code in to set initial block size to 1, otherwise it reports that the code in memory is 1 block smaller than it actually is.
