### ISSUE TITLE
+/IM.logon (sysoplist)

### ISSUE THREAD

**Issue by ThaDoctor72** [Pinacolada64/ImageBBS#27]
When editing a sysop's flags, there is no way to exit the menu. Options exist for flags 1-8, but neither [CR], Q, or backarrow will get you out.  
I had to break and goto1100 just to get back to the previous module.

**Comment by x-tec2017** [comment]
Tested on Hyperdrive, Thunderdrive, uIEC/SD2IEC and WinVICE.
Could not duplicate issue. The Return (Enter in VICE) always returns me to the prompt
A/dd E/dit D/elete L/ist Q/uit
Entering Q always exits back to the IM sub module.

**Comment by ThaDoctor72** [comment]
Try editing and existing sysop just the flags. (option 2)

**Comment by x-tec2017** [comment]
Did that. No problem exiting the flags (option 2) with the Return key.

**Comment by x-tec2017** [comment]
This issue has now been verified in Jay's copy of the Image 2.0 files only. Everyone else is not having this issue. It appears that somehow Jay has disabled the definition of r$ in his copy. As a quick fix for this problem and to but this issue to bed, for Jay only, in +/IM.logon at the beginning of line 4000 insert r$=chr$(13):

**Comment by Pinacolada64** [comment]
Can this issue be closed, @ThaDoctor72 ?

**Comment by x-tec2017** [comment]
Yes. Close this issue.
