### ISSUE TITLE
+.UU does not edit information

### ISSUE THREAD

**Issue by ThaDoctor72** [Pinacolada64/ImageBBS#29]
Issue 1: Ignores the menu mode.  After selecting the user, the data is displayed in cursor menu mode.

Issue 2: No data can be selected
When selecting (either by cursor/return or letter) any item, the screen clears twice, then returns to view mode. No entry prompts appear, and no records are changed.

**Comment by x-tec2017** [comment]
You're right. +.UU (I think) is an unfinished user editor program that was being worked on for 2.0. It's included on the disk for anyone who thinks they can fix it and make it work as the original programmers intended.

Use +.ED to edit user records in the meantime.

**Comment by Pinacolada64** [comment]
How's this going?

**Comment by x-tec2017** [comment]
It's not worth the effort of fixing. Even if all the fields could be edited, +.ED is still more efficient in editing the u.config records.

**Comment by Pinacolada64** [comment]
I might still work on it someday. Can always reopen in the future. Closing for now.

**Comment by ThaDoctor72** [comment]
Yes, consider it a feature request.
