### ISSUE TITLE
Idle screen terminal locks up before selecting transfer protocol

### ISSUE THREAD

**Issue by Pinacolada64** [Pinacolada64/ImageBBS#3]
From @xtec2017:

> ? I'm stuck on something that maybe you can help with in Image 2.0.
> Go into Image Term by holding down the CONTROL key and hitting the left arrow.
Select 3) Term Parameters
Select 3)  U/D Protocol
The system gets stuck in line 2500

> I've traced it this far:
in +.t
`3210 gets an$'
'3210 gosub3006'
'         3006 converts an$ to a    (a=3)'
'3212 on(3)goto3228'
'3228 gosub1666'
'          1666 sets im=4: goto2406'
'          2406 sets a$=params:goto2500'
'          2500 gosub2510'
'                   2510 loads "im.params"'
'                   2512 return'
'          2500 gets stuck here'`

> it should continue in line 2500 with `is=is+1:im$(is)=im$` then fall to 2502
`2502 gosub60000:new60000:is=is-1:if is then a$=im$(is):gosub 2510
2504 return`

**Comment by Pinacolada64** [comment]
As we've discovered, `im` creates an array to keep track of which `im.*` modules it's loaded. Maybe it loses track of the index? I see no reason for it to totally lock up right there.

**Comment by x-tec2017** [comment]
I think the reason the computer locks up when selecting U/D Protocol, is because we exceeded available memory. When it locks up at 2500 I see M=65454

**Comment by Pinacolada64** [comment]
Ouch! I'll double-check that.

**Comment by Pinacolada64** [comment]
Hmm, I see what you're saying about `M=65434`. I went into the VICE monitor and I see it's stuck in an (infinite?) loop from `$b56e - $b699` afterwards. Hmm. That's stock Commodore garbage collection. Hmm. I'm going to try waiting it out (or kicking VICE into Warp mode) - maybe that will shed some light onto this.

**Comment by Pinacolada64** [comment]
Not particularly. Quick hack: transplant lines from `im.params` to `+.t` and see if that at least moves us forward.

**Comment by Pinacolada64** [comment]
I'm closing this, it was fixed with `+.t` cuts.
