### ISSUE TITLE
+.SB previous/next commands

### ISSUE THREAD

**Issue by ThaDoctor72** [Pinacolada64/ImageBBS#32]
Is it just me, or does > and < not switch between sub/boards like UD and UX?

**Comment by x-tec2017** [comment]
I thought it was just you but apparently not. I tested this issue on WN2, IMW, ATL, Atlantis II and on my conversion of SYS 1.2 to 2.0. It works everywhere except on Atlantis II. Entering > stays on the same board and entering < returns "Unknown Board Number"
Note: >> and << switch between SIGs if more than one SIG is defined (on boards where > and < work)

**Comment by x-tec2017** [comment]
I think I know what's causing the error you are seeing with the > Next and < previous commands.
Either run +.sigedit or use the Sysop Menu and select Editor Utils and Run Sigedit to go into your SIG. Make sure the SB is configured as (Yes) and the numbers for your message boards are listed.  

There is a possibility that the way your drives are configured in VICE causes the same problem as experienced on uIEC drives with the renaming file function.  If so, when you configure your SB UD and UX assignments in +.reledit or from the Sysop Menus, adding entries to one area causes them to disappear from the other two areas. If that's the case, you need the uiec fixes.d64 file which github won't let me upload. I'll send it to you via messenger.

**Comment by DarkstarII** [comment]
The Sig changes saying Yes did resolve the issue for me. My prior build of Image 2.0 worked without issue. The newer TEST build I made did not until your recommended fix X-Tec Thanks.

**Comment by x-tec2017** [comment]
I revised the two files, +/SM.consig1 and +/SM.consig2 which now fully automate the correct conversion of the e.Sig files. After installing these changes, you will no longer need to edit the flags in the sigedit program. Read the "consig.txt" seq file included. I sent an updated .d64 file to each of you, Ryan, Jay and Mark.
Check them out and if everyone agrees this issue is fixed, this issue can be closed by the originator.

**Comment by x-tec2017** [comment]
Has anyone tried the new +/SM.consig1 and 2 files yet? I'm wondering if they work well for everyone and if this issue can be closed.

**Comment by ThaDoctor72** [comment]
I was looking for that file, but didn't know exactly where to look. (Email, FB, etc)

**Comment by ThaDoctor72** [comment]
Using the instructions provided in the consig1&2 update, I re-converted my sigs and can confirm the proper response to > < commands.  It was also apparent after launching sigedit that the open/close flags were no longer inverted.
Previously, a sig with subs and ud's but no ux was displayed as 001.
Now it displays the flags as 110.  Sigs now appear and are selectable when entering SB.
Issue can be closed.

**Comment by x-tec2017** [comment]
Good news. I know the change works for Mark and I've tested it extensively on three different media, Lt.K, Thunderdrive and uIEC.  Let's give Ryan time to get up to speed with R2 and all the changes and if he concurs with this fix, go ahead and close it.

**Comment by ThaDoctor72** [comment]
My test was done in WinVice using FD-4000 emulation media.

**Comment by x-tec2017** [comment]
You can close this issue.
