### ISSUE TITLE
Drive activity light stays on after 10 minutes idle

### ISSUE THREAD

**Issue by x-tec2017** [Pinacolada64/ImageBBS#33]

**Comment by x-tec2017** [comment]
Image is opening the e.stats file to update the records for idle time but is not closing the file when finished.

Solution:  in +.lo at the end of line 3482, add  :close2

**Comment by Pinacolada64** [comment]
I've added that to `+.lo` - got some other improvements slated for it too.

* Not being prompted for leaving feedback or showing the logoff screen if logged in from immediate or console mode
* Temporary Reservation PassWord clears itself after successful login

**Comment by Pinacolada64** [comment]
Okay.

So does `close 2` close this issue?

**Comment by x-tec2017** [comment]
Yes, this issue is now closed.
