### ISSUE TITLE
e.idle file is not being written

### ISSUE THREAD

**Issue by x-tec2017** [Pinacolada64/ImageBBS#35]
The beginning of line 3484 of +.lo should be changed 
from:
3484 on1goto3490:
to:
3484 onigoto3490:

**Comment by ThaDoctor72** [comment]
Is that what keeps the drive activity light on the whole time during waiting for call?

**Comment by x-tec2017** [comment]
Yes, I think so. It does on my uIEC drive and on my Thunderdrive. Adding the close2 at the end of the line fixed that.

**Comment by x-tec2017** [comment]
This fix has been added to the fixes after r2 disk and the issue is closed.
