### ISSUE TITLE
+/IM.access missing from R2 set

### ISSUE THREAD

**Issue by ThaDoctor72** [Pinacolada64/ImageBBS#36]
I didn't discover this until I went to add the changed lines in +/IM.access.  I have the i/IM.access from the December set, but I'm not sure what has been changed since then.

**Comment by x-tec2017** [comment]
I'm looking at the directory of the IMG2.0 R2 D1.D81 file that I uploaded to Facebook and I see +/IM.access included. It's an 8 block prg file and appears just below +/GF.UX and just above +/IM.ecs

**Comment by ThaDoctor72** [comment]
Chalk it up to old man eyes. Sorry for the red flag.
