### ISSUE TITLE
More? prompt during logon

### ISSUE THREAD

**Issue by ThaDoctor72** [Pinacolada64/ImageBBS#38]
This didn't start happening until I set the "lines per screen" setting for sysop user.  I wonder if this was somehow responsible for issue #15 where we got unwanted prompts.
Suggest setting a temporary lines/screen variable until the user profile is loaded.
See screenshot:
![AltText](http://www.hoyvision.com/pub/more-issue.JPG)

**Comment by ThaDoctor72** [comment]
Tried both and didn't have any affect. 
Behavior is the same whether or not the window shade is down. (F1)

**Comment by x-tec2017** [comment]
Whether or not the ...More? (Y/n) prompt appears during logon is a user definable function unique to each user account setting. There are two ways to change the more prompt setting for your account, either by the MP command or by using EP to edit your parameters. The three choices are Off, On or Messages only. If you set your more prompt to Off, you will not see the ...More? (Y/n) prompt during logon or anywhere else on the board. If set to Messages Only, you will see the prompt during logon but it gets turned off during the logon process and stays off unless you enter the message boards. Exiting the message boards will turn the more prompt back off. If you have your more prompt set to On, then your will see the prompt during logon and it will stay on for all areas of the board.  If you are logged on in local mode when you make a change to your user account, you must log off using the O command and answer Yes to the "Update User File?" question during logoff for the changes to take effect. Simply using the f7 key to remove the check mark on the left of Loc on the light bar will not save the changes. If changes were made while logged on remotely, they are automatically saved during logoff and will be active at your next logon.

**Comment by x-tec2017** [comment]
I think Image is operating the way it's supposed to and this non-issue can be closed.

**Comment by Pinacolada64** [comment]
I don't know, it seems annoying to me. It's been on my list to look at.

**Comment by ThaDoctor72** [comment]
This issue is unrelated to the more prompt on/off/message-only issue. 
Turns out it was bad information (total calls, 5928 of them) written to the columns (record 11) of u.config for the sysop account.  This happened somehow during conversion, but I verified that by correcting that record manually, the issue stopped.

**Comment by x-tec2017** [comment]
LOL...
5928 in u.config columns setting is not total calls, it is a number that Image 2.0 uses to define line length and lines per page in each user account. It might be 40 or 80 or some other number if the u.config file is a conversion from 1.2 but as each user logs on to his new 2.0 account, he will be asked for the number of lines he can display and the number in that field will be changed accordingly.

**Comment by ThaDoctor72** [comment]
HAHA. Now that is funny.  As a sense of historical irony would have it,
that is precisely how many calls my BBS had on it when I converted it. Thus
the confusion.
Great, now I've earned a "lemme tell you about this guy" title in your next
programmers meeting.
