### ISSUE TITLE
e.access writing garbage

### ISSUE THREAD

**Issue by ThaDoctor72** [Pinacolada64/ImageBBS#42]
Not sure what is causing it, but e.access seems to constantly add lines to the file until eventually it is completely overwritten.

![image](https://user-images.githubusercontent.com/42911819/47277869-47b84400-d592-11e8-8baa-e06296acc5fe.png)

**Comment by Pinacolada64** [comment]
Uh oh. That data that's getting written into `e.access` is what would get written to `e.idle <day>`, the newly integrated "idle logging" feature. Issue #35 put a `close 2` in `+.lo`, line 3482. Looks like `e.idle <day>` didn't get closed before `e.access` was opened. I wonder if this happens during logon.

**Comment by ThaDoctor72** [comment]
My lines reflect the changes from issue #35 but what if i is positive and never reaches the end of 3484 to get the close statement?
The rest of 3482 would be ignored since we're using "if".

3482 ifithenx=x+11:gosub1025:x=x+16:gosub1025:close2
3484 onigoto3490:c$="e.idle "+left$(am$,1)+",s"

**Comment by ThaDoctor72** [comment]
It happens more for each event.  I was having disconnect issues, so whenever I would startup the BBS, it would get a fake connect, do it about 10 times, then finally settle down.  Getting chatter from TCPser.  By the end of the day, the file looked like this:
![image](https://user-images.githubusercontent.com/42911819/47333448-ed31ed00-d650-11e8-8a67-83aa0dd672f5.png)

**Comment by x-tec2017** [comment]
I've reviewed this and other disk errors generated from this disk image and I'm pretty sure they are being generated by a non-standard disk partitioning and file arrangement.

**Comment by ThaDoctor72** [comment]
It's happening to e.macro now. 
![image](https://user-images.githubusercontent.com/42911819/48046080-f34fbf80-e160-11e8-96f0-b71f6650d2eb.png)

**Comment by Pinacolada64** [comment]
Ick. I'm sorry about this. For now, I'd just change line 3484's `on i goto 3490` to `goto 3490:`(rest of line). Should kill the whole feature.

(modified `+.lo` I'm working on:)
https://github.com/Pinacolada64/ImageBBS/blob/0865d16c003d6cfd5820f75a4072ffd9751ad9a7/v2/core/plus_lo.lbl#L454

`e.idle <day>` isn't getting re-opened, and it's just writing to the currently opened file, that much is clear. I can upload an updated `+.lo` and `+/lo.misc` file to your BBS tomorrow if you want to try them out.

**Comment by x-tec2017** [comment]
Ryan, whatever you've been working on for the past couple of months, please go ahead and upload it to IMW. I would like to see what you've done.  Make sure to use the "Upload 2.0 Files Here" UD library for your uploads.

**Comment by ThaDoctor72** [comment]
Okay.. Here we have another file that is getting written to, and I've closed off 3484 to match the above.
![image](https://user-images.githubusercontent.com/42911819/48244453-d3fca080-e3b3-11e8-89e6-d644ef64fada.png)
Seems the data between e.macros and e.access is getting swapped.  Also, I have (on occasion) had issues with my user account (in u.config) become littered with modem idle data, even after closing that line in +.lo

**Comment by ThaDoctor72** [comment]
Further investigation of this issue reveals that these two files (e.access and e.macro) are getting crossed. Just by sitting at the main prompt (1811) so they are not getting closed somewhere. 
I was able to test this by having a hot standby of each file on a different drive, and just copying the good one over when the live file gets changed.  At no time will both of the files be correct.   If e.access is normal, e.macros will be hosed, and vice versa. My mods to IM have been strictly aesthetic so far, nothing that would affect file closing/opening/getting/writing.  Is anyone else seeing this issue?
Try to recreate by having macros configured and enabled, then go to ST to check your stats, twice.

**Comment by Pinacolada64** [comment]
@ThaDoctor72: is this still an issue?

**Comment by ThaDoctor72** [comment]
No.
