### ISSUE TITLE
User count is set to 141 when new BBS configured

### ISSUE THREAD

**Issue by Pinacolada64** [Pinacolada64/ImageBBS#5]
Not sure where this is happening. Run `+.alpha/ind` to fix.

**Comment by Pinacolada64** [comment]
im: during new BBS setup, record #12 in `e.data` is set to ^ (141), then read back later as ur=141
3300- is where e.data is set up

Looked through Jack's `sub.handles`/`sub.misc` files, not as extensive as Al's `im.misc`.
However, Jack's `i/su.config` creates `u.index` differently. I'll try that.

```
4074 &"Creating {f5}u.index{f5}....":dr=6:gosub3:a$=dr$+"u.index":print#15,"s"a$
4075 a%(0)=1:a%(1)=1:&,60,3,0,a%(0),4,a$,dv%:close15:&"Done!"
```

His line 3 is our line 1010 (figures out which device/drive is assigned to the user disk). A struct is created with the `&,60...` call, and saved.

**Comment by Pinacolada64** [comment]
This has been incorporated into Dec 17th's `im` module. Seems to work! `ur` is set to 2, `u.index` created properly with the user count set to 1.

**Comment by x-tec2017** [comment]
Where is the Dec 17 im module?

**Comment by Pinacolada64** [comment]
I'll upload it to the WiFi BBS.

**Comment by x-tec2017** [comment]
That would be great. Thanks.

**Comment by Pinacolada64** [comment]
I'm closing this issue, I believe the Dec. 17th IM revision fixes it.

**Comment by x-tec2017** [comment]
I agree.
Haven't heard from you in awhile. Lots has been done since then. New fixes,
mods and a game added in the Image 2.0 Support UD's.
