### ISSUE TITLE
Access level 9 given all permissions at BBS setup

### ISSUE THREAD

**Issue by Pinacolada64** [Pinacolada64/ImageBBS#6]
It would be nice not to have to manually set all the flags on the sysop account when you're first setting up your BBS.

**Comment by Pinacolada64** [comment]
This has been patched. Access level 9 is given full access/"unlimited everything" by default, no need to go into `IM` and set flags anymore.

**Comment by x-tec2017** [comment]
Where's this patch? Is it on github somewhere?

**Comment by Pinacolada64** [comment]
https://github.com/Pinacolada64/ImageBBS/commit/462ce5e88b07102ba7b73de5e5b4f8016f75fb28
